sudo: required
dist: trusty

env:
  - ANDROID_HOME=$PWD/

before_install:
- mysql -u root --password="" < server/src/test/java/it/unibo/drescue/database/travis.sql

install:
- wget --quiet --output-document=tools.zip https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
- unzip -qq tools.zip
- echo y | tools/bin/sdkmanager "platforms;android-25"
- echo y | tools/bin/sdkmanager "platform-tools"
- echo y | tools/bin/sdkmanager "build-tools;25.0.2"
- echo y | tools/bin/sdkmanager "extras;android;m2repository"
- echo y | tools/bin/sdkmanager "extras;google;m2repository"
  
language: java
jdk: oraclejdk8
android:
  components:
    # For the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.1

    # The SDK version used to compile your project
    - android-25
    - android-19

    # Additional components
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-25
    - sys-img-armeabi-v7a-android-19

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
- chmod +x ./gradlew
- './gradlew clean build'

services:
  - rabbitmq
  - mysql